name: tanksense
description: Sistema TankSense - Monitoramento de Tanque

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mysql1: ^0.20.0
  http: ^1.1.0
  intl: ^0.18.0
  mysql_client: ^0.0.27
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0